
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 9;
  public static final int GE = 16;
  public static final int pidentifier = 3;
  public static final int SEMI = 21;
  public static final int ENDDO = 30;
  public static final int FOR = 31;
  public static final int MINUS = 7;
  public static final int WRITE = 37;
  public static final int LT = 13;
  public static final int IN = 18;
  public static final int ENDFOR = 35;
  public static final int PLUS = 6;
  public static final int ASSIGN = 22;
  public static final int IF = 23;
  public static final int ENDWHILE = 29;
  public static final int LE = 15;
  public static final int LEFT = 4;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MODULO = 10;
  public static final int NEQ = 12;
  public static final int EQ = 11;
  public static final int DECLARE = 17;
  public static final int FROM = 32;
  public static final int TIMES = 8;
  public static final int COLON = 20;
  public static final int ENDIF = 26;
  public static final int ELSE = 25;
  public static final int READ = 36;
  public static final int TO = 33;
  public static final int WHILE = 27;
  public static final int THEN = 24;
  public static final int END = 19;
  public static final int DOWNTO = 34;
  public static final int RIGHT = 5;
  public static final int num = 2;
  public static final int GT = 14;
  public static final int DO = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "num",
  "pidentifier",
  "LEFT",
  "RIGHT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MODULO",
  "EQ",
  "NEQ",
  "LT",
  "GT",
  "LE",
  "GE",
  "DECLARE",
  "IN",
  "END",
  "COLON",
  "SEMI",
  "ASSIGN",
  "IF",
  "THEN",
  "ELSE",
  "ENDIF",
  "WHILE",
  "DO",
  "ENDWHILE",
  "ENDDO",
  "FOR",
  "FROM",
  "TO",
  "DOWNTO",
  "ENDFOR",
  "READ",
  "WRITE"
  };
}

